import { createHash } from "node:crypto";
import { lstat, readFile, readdir, stat } from "node:fs/promises";
import { join } from "node:path";
import { HarnessError, fail } from "./errors.mjs";
import { firstSymlinkInPath, resolveInside } from "./path-safety.mjs";
import { readRepoText } from "./repo-io.mjs";

// Skills Module shared core: control-path resolution, registry/lock schemas,
// external SKILL.md parser, entity digests, gitignore projection and the
// Runtime readiness model. The mutation engine lives in
// src/distribution/skills-sync.mjs; both share these schemas and error codes.

export const SKILLS_ROOT = ".agents/skills";
export const REGISTRY_REL = ".agents/skills.sources.json";
export const LOCK_REL = ".agents/skills.lock.json";
export const SOURCE_REGISTRY_REL = "source/.agents/skills.sources.json";
export const SOURCE_LOCK_REL = "source/.agents/skills.lock.json";
export const SKILLS_GITIGNORE_HEADER = "# Generated by ai-vibe-demo-kit skills; managed external skills, do not edit.";
export const STAGING_DIRNAME = ".staging";
export const SOURCES_DIRNAME = ".sources";
export const PINNED_SHA = /^[0-9a-f]{40}$/;
export const SAFE_SKILL_NAME = /^[A-Za-z0-9._-]+$/;
export const RESERVED_SKILL_NAMES = new Set([".", "..", SOURCES_DIRNAME, STAGING_DIRNAME]);
export const SOURCE_ID = /^[A-Za-z0-9][A-Za-z0-9._-]*$/;
const TRACK_KINDS = new Set(["branch", "tag", "commit"]);
const LEDGER_REL = ".harness/install-lock.json";
const DISTRIBUTION_MANIFEST_REL = "source/manifest.json";
const PACKAGE_NAME = "ai-vibe-demo-kit";

const isObject = (value) => value !== null && typeof value === "object" && !Array.isArray(value);
const nonEmpty = (value) => typeof value === "string" && value.trim() !== "";

// ---------------------------------------------------------------------------
// Control paths: one decision, never a per-file fallback.
// 1. valid install ledger -> root .agents/*
// 2. package-only source/manifest.json (the kit source repository) -> source/.agents/*
// 3. anything else -> root .agents/*
// Materialization is always the root-level .agents/skills/.
// ---------------------------------------------------------------------------

async function hasValidInstallLedger(root) {
  const target = join(root, LEDGER_REL);
  try {
    const stat = await lstat(target);
    if (stat.isSymbolicLink() || !stat.isFile()) return false;
    const value = JSON.parse(await readFile(target, "utf8"));
    return isObject(value)
      && value.schemaVersion === 1
      && new Set(["installed", "residual"]).has(value.installationState)
      && isObject(value.package)
      && value.package.name === PACKAGE_NAME;
  } catch {
    return false;
  }
}

async function hasPackageOnlySourceManifest(root) {
  const target = join(root, DISTRIBUTION_MANIFEST_REL);
  try {
    const stat = await lstat(target);
    if (stat.isSymbolicLink() || !stat.isFile()) return false;
    const value = JSON.parse(await readFile(target, "utf8"));
    if (!isObject(value) || value.schemaVersion !== 1 || !isObject(value.package) || value.package.name !== PACKAGE_NAME || !Array.isArray(value.files)) return false;
    const self = value.files.filter((entry) => isObject(entry) && entry.sourcePath === DISTRIBUTION_MANIFEST_REL && entry.kind === "package-only" && entry.targetPath === null);
    return self.length === 1;
  } catch {
    return false;
  }
}

export async function resolveSkillControlPaths(root) {
  if (await hasValidInstallLedger(root)) {
    return { basis: "install-ledger", registryPath: REGISTRY_REL, lockPath: LOCK_REL, skillsRoot: SKILLS_ROOT };
  }
  if (await hasPackageOnlySourceManifest(root)) {
    return { basis: "package-source", registryPath: SOURCE_REGISTRY_REL, lockPath: SOURCE_LOCK_REL, skillsRoot: SKILLS_ROOT };
  }
  return { basis: "root", registryPath: REGISTRY_REL, lockPath: LOCK_REL, skillsRoot: SKILLS_ROOT };
}

// ---------------------------------------------------------------------------
// Registry (skills.sources.json) schema: strict, unknown fields are errors.
// ---------------------------------------------------------------------------

const REGISTRY_FIELDS = new Set(["version", "description", "skillsRoot", "sources"]);
const REGISTRY_SOURCE_FIELDS = new Set(["id", "repo", "path", "track", "only", "exclude"]);

function registryError(message) {
  return new HarnessError("E_SKILLS_REGISTRY_INVALID", message, { exitCode: 2 });
}

function normalizeRelativePath(raw, field, { allowDot }, error = registryError) {
  if (typeof raw !== "string") throw error(`${field} must be a string; use a project-relative POSIX path.`);
  const trimmed = raw.trim();
  if (trimmed === "") throw error(`${field} must not be empty; use "." for the repository root.`);
  if (trimmed.startsWith("/") || /^[A-Za-z]:/.test(trimmed)) throw error(`${field} must be relative, got "${trimmed}".`);
  if (trimmed.includes("\\")) throw error(`${field} must use POSIX "/" separators, got "${trimmed}".`);
  const segments = trimmed.split("/").filter((part) => part !== "" && part !== ".");
  if (segments.some((part) => part === "..")) throw error(`${field} must not contain "..", got "${trimmed}".`);
  if (segments.length === 0) {
    if (allowDot) return ".";
    throw error(`${field} must name a directory inside the project, not the project root itself.`);
  }
  return segments.join("/");
}

function normalizePatterns(raw, field) {
  if (raw === undefined) return undefined;
  if (!Array.isArray(raw) || raw.length === 0 || raw.some((item) => !nonEmpty(item))) {
    throw registryError(`${field} must be a non-empty array of non-empty strings; use skill names or directory prefixes ending in "/".`);
  }
  const items = raw.map((item) => item.trim());
  if (new Set(items).size !== items.length) throw registryError(`${field} must not contain duplicates.`);
  return [...items].sort();
}

export function parseSkillRegistryValue(value) {
  if (!isObject(value)) throw registryError("skills registry must be a JSON object.");
  if (value.version !== 2) {
    throw new HarnessError("E_SKILLS_REGISTRY_VERSION", `skills registry version must be 2, got ${JSON.stringify(value.version)}; set "version": 2 with track {kind,value} per source.`, { exitCode: 2 });
  }
  for (const key of Object.keys(value)) {
    if (!REGISTRY_FIELDS.has(key)) throw registryError(`unknown registry field "${key}"; allowed: ${[...REGISTRY_FIELDS].join(", ")}.`);
  }
  if (value.description !== undefined && !nonEmpty(value.description)) throw registryError("description must be a non-empty string when present.");
  const skillsRoot = value.skillsRoot === undefined
    ? SKILLS_ROOT
    : normalizeRelativePath(value.skillsRoot, "skillsRoot", { allowDot: false });
  if (skillsRoot !== SKILLS_ROOT) throw registryError(`skillsRoot must be "${SKILLS_ROOT}"; materialization is always the root-level skills directory.`);
  if (!Array.isArray(value.sources)) throw registryError('sources must be an array (use [] to disable external skills).');
  const ids = new Set();
  const sources = value.sources.map((entry, index) => {
    const at = `sources[${index}]`;
    if (!isObject(entry)) throw registryError(`${at} must be an object.`);
    for (const key of Object.keys(entry)) {
      if (!REGISTRY_SOURCE_FIELDS.has(key)) throw registryError(`${at} has unknown field "${key}"; allowed: ${[...REGISTRY_SOURCE_FIELDS].join(", ")}.`);
    }
    if (!nonEmpty(entry.id) || !SOURCE_ID.test(entry.id.trim())) throw registryError(`${at}.id must match ${SOURCE_ID}.`);
    const id = entry.id.trim();
    if (ids.has(id)) throw registryError(`duplicate source id "${id}".`);
    ids.add(id);
    if (!nonEmpty(entry.repo)) throw registryError(`${at}.repo must be a non-empty Git remote or local path.`);
    const repo = entry.repo.trim();
    if (/^https?:\/\//i.test(repo)) {
      let url;
      try { url = new URL(repo); }
      catch { throw registryError(`${at}.repo is not a valid URL; use a clone URL without embedded credentials.`); }
      if (url.username !== "" || url.password !== "") {
        throw registryError(`${at}.repo (${url.protocol}//${url.host}/…) embeds credentials; remove userinfo and configure a Git credential helper or SSH key instead.`);
      }
    }
    const sourcePath = normalizeRelativePath(entry.path, `${at}.path`, { allowDot: true });
    if (!isObject(entry.track) || !TRACK_KINDS.has(entry.track.kind)) throw registryError(`${at}.track.kind must be one of branch|tag|commit.`);
    if (!nonEmpty(entry.track.value)) throw registryError(`${at}.track.value must be a non-empty string.`);
    const trackValue = entry.track.value.trim();
    if (entry.track.kind === "commit" && !PINNED_SHA.test(trackValue)) throw registryError(`${at}.track.value for kind "commit" must be a 40-char lowercase SHA.`);
    if (entry.track.kind !== "commit" && (/[\s~^:?*[\]\\]/.test(trackValue) || trackValue.includes("..") || trackValue.startsWith("-") || trackValue.endsWith("/") || trackValue.endsWith(".lock"))) {
      throw registryError(`${at}.track.value "${trackValue}" is not a valid Git ref name.`);
    }
    const only = normalizePatterns(entry.only, `${at}.only`);
    const exclude = normalizePatterns(entry.exclude, `${at}.exclude`);
    return {
      id,
      repo,
      path: sourcePath,
      track: { kind: entry.track.kind, value: trackValue },
      ...(only ? { only } : {}),
      ...(exclude ? { exclude } : {}),
    };
  });
  return { version: 2, skillsRoot, sources, ...(value.description !== undefined ? { description: value.description } : {}) };
}

export function parseSkillRegistryText(raw) {
  let value;
  try { value = JSON.parse(raw); }
  catch (error) { throw registryError(`skills registry is not valid JSON: ${error.message}`); }
  return parseSkillRegistryValue(value);
}

// ---------------------------------------------------------------------------
// Lock (skills.lock.json) schema: resolved SHAs, tree digests, licenses.
// ---------------------------------------------------------------------------

const LOCK_SOURCE_FIELDS = new Set(["id", "repo", "path", "track", "only", "exclude", "resolved", "licenseFiles", "skills"]);

function lockError(message) {
  return new HarnessError("E_SKILLS_LOCK_INVALID", `${message} Run "ai-vibe-demo-kit skills update" to regenerate the lock.`, { exitCode: 2 });
}

export function canonicalSourceSpec(source) {
  return {
    id: source.id,
    repo: source.repo,
    path: source.path,
    track: { kind: source.track.kind, value: source.track.value },
    ...(source.only ? { only: [...source.only].sort() } : {}),
    ...(source.exclude ? { exclude: [...source.exclude].sort() } : {}),
  };
}

export function sourceSpecEqual(manifestSource, lockSource) {
  return JSON.stringify(canonicalSourceSpec(manifestSource)) === JSON.stringify(canonicalSourceSpec(lockSource));
}

export function licenseLocalPath(skillsRoot, sourceId, repoPath) {
  return `${skillsRoot}/${SOURCES_DIRNAME}/${sourceId}/licenses/${repoPath}`;
}

export function parseSkillLockValue(value) {
  if (!isObject(value)) throw lockError("skills lock must be a JSON object.");
  if (value.version !== 2) {
    throw new HarnessError("E_SKILLS_LOCK_VERSION", `skills lock version must be 2, got ${JSON.stringify(value.version)}; v1 locks are not upgraded in place.`, { exitCode: 2 });
  }
  for (const key of Object.keys(value)) {
    if (!new Set(["version", "skillsRoot", "sources"]).has(key)) throw lockError(`unknown lock field "${key}".`);
  }
  let skillsRoot;
  try { skillsRoot = normalizeRelativePath(value.skillsRoot, "lock skillsRoot", { allowDot: false }, lockError); }
  catch (error) {
    if (error instanceof HarnessError && error.code === "E_SKILLS_LOCK_INVALID") throw error;
    throw lockError(error.message);
  }
  if (skillsRoot !== SKILLS_ROOT) throw lockError(`lock skillsRoot must be "${SKILLS_ROOT}".`);
  if (!Array.isArray(value.sources)) throw lockError("lock sources must be an array.");
  const ids = new Set();
  const names = new Map();
  const sources = value.sources.map((entry, index) => {
    const at = `lock sources[${index}]`;
    if (!isObject(entry)) throw lockError(`${at} must be an object.`);
    for (const key of Object.keys(entry)) {
      if (!LOCK_SOURCE_FIELDS.has(key)) throw lockError(`${at} has unknown field "${key}".`);
    }
    if (!nonEmpty(entry.id) || !SOURCE_ID.test(entry.id)) throw lockError(`${at}.id is missing or illegal.`);
    if (ids.has(entry.id)) throw lockError(`duplicate source id "${entry.id}".`);
    ids.add(entry.id);
    if (!nonEmpty(entry.repo)) throw lockError(`${at}.repo is missing.`);
    if (!nonEmpty(entry.path)) throw lockError(`${at}.path is missing.`);
    if (!isObject(entry.track) || !TRACK_KINDS.has(entry.track.kind) || !nonEmpty(entry.track.value)) throw lockError(`${at}.track is missing or illegal.`);
    if (!PINNED_SHA.test(entry.resolved ?? "")) throw lockError(`${at}.resolved must be a 40-char lowercase SHA, got ${JSON.stringify(entry.resolved)}.`);
    for (const field of ["only", "exclude"]) {
      if (entry[field] !== undefined && (!Array.isArray(entry[field]) || entry[field].some((item) => !nonEmpty(item)))) throw lockError(`${at}.${field} must be an array of non-empty strings.`);
    }
    if (!Array.isArray(entry.licenseFiles)) throw lockError(`${at}.licenseFiles must be an array.`);
    const licenseFiles = entry.licenseFiles.map((file, fileIndex) => {
      if (!isObject(file) || !nonEmpty(file.path) || !/^[0-9a-f]{64}$/.test(file.sha256 ?? "") || !nonEmpty(file.localPath)) {
        throw lockError(`${at}.licenseFiles[${fileIndex}] must declare path, sha256 and localPath.`);
      }
      if (file.path.includes("/") || file.path === "." || file.path === "..") throw lockError(`${at}.licenseFiles[${fileIndex}].path must be a repository-root file name.`);
      if (file.localPath !== licenseLocalPath(skillsRoot, entry.id, file.path)) throw lockError(`${at}.licenseFiles[${fileIndex}].localPath must be "${licenseLocalPath(skillsRoot, entry.id, file.path)}".`);
      return { path: file.path, sha256: file.sha256, localPath: file.localPath };
    });
    if (!Array.isArray(entry.skills) || entry.skills.length === 0) throw lockError(`${at}.skills must be a non-empty array.`);
    const skills = entry.skills.map((skill, skillIndex) => {
      if (!isObject(skill) || !SAFE_SKILL_NAME.test(skill.name ?? "") || RESERVED_SKILL_NAMES.has(skill.name) || !nonEmpty(skill.sourcePath) || !/^[0-9a-f]{64}$/.test(skill.treeDigest ?? "")) {
        throw lockError(`${at}.skills[${skillIndex}] must declare name, sourcePath and treeDigest.`);
      }
      if (skill.sourcePath !== "." && (skill.sourcePath.startsWith("/") || skill.sourcePath.split("/").some((part) => part === ".." || part === ""))) {
        throw lockError(`${at}.skills[${skillIndex}].sourcePath must be a safe repository-relative path.`);
      }
      const owner = names.get(skill.name);
      if (owner) throw lockError(`skill name "${skill.name}" is claimed by both "${owner}" and "${entry.id}".`);
      names.set(skill.name, entry.id);
      return { name: skill.name, sourcePath: skill.sourcePath, treeDigest: skill.treeDigest };
    });
    return { ...canonicalSourceSpec(entry), resolved: entry.resolved, licenseFiles, skills };
  });
  return { version: 2, skillsRoot, sources };
}

export function parseSkillLockText(raw) {
  let value;
  try { value = JSON.parse(raw); }
  catch (error) { throw lockError(`skills lock is not valid JSON: ${error.message}`); }
  return parseSkillLockValue(value);
}

export function registryMatchesLock(registry, lock) {
  if (!registry || !lock) return false;
  if (registry.skillsRoot !== lock.skillsRoot) return false;
  if (registry.sources.length !== lock.sources.length) return false;
  const lockById = new Map(lock.sources.map((source) => [source.id, source]));
  return registry.sources.every((source) => {
    const locked = lockById.get(source.id);
    return locked && sourceSpecEqual(source, locked);
  });
}

// ---------------------------------------------------------------------------
// External SKILL.md parser: extra top-level fields, quoted values and the
// YAML block scalars >, >-, |, |-. name/description must appear exactly once
// and be non-empty. The bundled skill keeps the strict two-field parser in
// src/runtime/validation/workflow.mjs; materialization never rewrites bytes.
// ---------------------------------------------------------------------------

const FRONTMATTER = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)([\s\S]*)$/;
const BLOCK_MARKERS = new Set([">", ">-", "|", "|-"]);

function parseBlockScalar(lines, start, marker) {
  const block = [];
  let index = start;
  while (index < lines.length && (/^[ \t]/.test(lines[index]) || lines[index].trim() === "")) {
    block.push(lines[index]);
    index += 1;
  }
  while (block.length > 0 && block.at(-1).trim() === "") block.pop();
  const indents = block.filter((line) => line.trim() !== "").map((line) => line.length - line.trimStart().length);
  const depth = indents.length > 0 ? Math.min(...indents) : 0;
  const stripped = block.map((line) => line.trim() === "" ? "" : line.slice(depth));
  let value;
  if (marker.startsWith(">")) {
    // folded: line breaks between non-empty lines become one space
    let text = "";
    for (const line of stripped) {
      if (line === "") text += "\n";
      else text += text === "" || text.endsWith("\n") ? line : ` ${line}`;
    }
    value = text;
  } else {
    value = stripped.join("\n");
  }
  if (!marker.endsWith("-") && value !== "") value += "\n";
  return { value, next: index };
}

export function parseExternalSkillDocument(content) {
  const match = FRONTMATTER.exec(content);
  if (!match) return null;
  const lines = match[1].split(/\r?\n/);
  const metadata = {};
  let index = 0;
  while (index < lines.length) {
    const raw = lines[index];
    if (raw.trim() === "") { index += 1; continue; }
    if (/^[ \t]/.test(raw)) return null;
    const entry = /^([A-Za-z0-9_-]+):(?:[ \t]+(.*))?$/.exec(raw);
    if (!entry) return null;
    const key = entry[1];
    if (Object.hasOwn(metadata, key)) return null;
    const inline = entry[2] ?? "";
    if (BLOCK_MARKERS.has(inline.trim())) {
      const block = parseBlockScalar(lines, index + 1, inline.trim());
      metadata[key] = block.value;
      index = block.next;
      continue;
    }
    let value = inline.trim();
    if (value.length >= 2 && ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'")))) value = value.slice(1, -1);
    metadata[key] = value;
    index += 1;
  }
  return { metadata, body: match[2] };
}

export function externalSkillIdentity(content) {
  const document = parseExternalSkillDocument(content);
  if (!document) return { ok: false, problem: "frontmatter is invalid" };
  const { name, description } = document.metadata;
  if (!nonEmpty(name)) return { ok: false, problem: 'frontmatter "name" is missing or empty' };
  if (!nonEmpty(description)) return { ok: false, problem: 'frontmatter "description" is missing or empty' };
  return { ok: true, name, description, metadata: document.metadata };
}

// ---------------------------------------------------------------------------
// Digests: sorted POSIX paths + type/executable bit + length + bytes.
// ---------------------------------------------------------------------------

export function sha256Hex(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

export function digestEntries(entries) {
  const sorted = [...entries].sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  const hash = createHash("sha256");
  for (const entry of sorted) {
    hash.update(entry.path, "utf8");
    hash.update("\0");
    hash.update(entry.executable ? "exec" : "file");
    hash.update("\0");
    hash.update(String(entry.bytes.length));
    hash.update("\0");
    hash.update(entry.bytes);
  }
  return hash.digest("hex");
}

// Directory inspection used by readiness and the sync engine alike.
// "missing" | "unsafe" (symlink/socket/unreadable -> invalid, exit 2) | "present".
export async function inspectSkillDirectory(root, name) {
  const base = resolveInside(root, `${SKILLS_ROOT}/${name}`);
  if (!base) return { state: "unsafe", digest: null };
  if (await firstSymlinkInPath(root, base)) return { state: "unsafe", digest: null };
  const entries = [];
  async function walk(dir, rel) {
    let listing;
    try { listing = await readdir(dir, { withFileTypes: true }); }
    catch (error) {
      if (error.code === "ENOENT") return "missing";
      return "unsafe";
    }
    for (const item of listing) {
      const itemAbs = join(dir, item.name);
      const itemRel = rel ? `${rel}/${item.name}` : item.name;
      if (item.isSymbolicLink() || (!item.isFile() && !item.isDirectory())) return "unsafe";
      if (item.isDirectory()) {
        const nested = await walk(itemAbs, itemRel);
        if (nested !== "present") return nested;
        continue;
      }
      try {
        const info = await stat(itemAbs);
        const bytes = await readFile(itemAbs);
        entries.push({ path: itemRel, executable: (info.mode & 0o111) !== 0, bytes });
      } catch {
        return "unsafe";
      }
    }
    return "present";
  }
  const state = await walk(base, "");
  return { state, digest: state === "present" ? digestEntries(entries) : null };
}

// Deterministic gitignore projection: lock-owned skills + provenance/staging;
// the generated file itself stays committable via the negation line.
export function expectedGitignore(skillNames) {
  const lines = [
    SKILLS_GITIGNORE_HEADER,
    ...[...skillNames].sort().map((name) => `/${name}/`),
    `/${SOURCES_DIRNAME}/`,
    `/${STAGING_DIRNAME}/`,
    "!.gitignore",
    "",
  ];
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Runtime readiness model. Three tiers:
//   valid=false            -> exit 2 (registry missing/invalid, unsafe paths,
//                             name mismatch, catalog/source closure broken)
//   valid=true, ready=false -> exit 1 (lock missing/stale -> skills update;
//                             required entity missing/drifted -> skills sync)
//   valid=true, ready=true  -> exit 0
// Optional skills only produce warnings.
// ---------------------------------------------------------------------------

const issue = (code, message, facts = null, repair = null) => ({ code, message, facts, repair });
const UPDATE_REPAIR = 'Run "ai-vibe-demo-kit skills update" to resolve sources and regenerate the lock.';
const SYNC_REPAIR = 'Run "ai-vibe-demo-kit skills sync" to materialize the locked skills.';

export async function readSkillRegistry(root, control) {
  try {
    return parseSkillRegistryText(await readRepoText(root, control.registryPath, "skills registry"));
  } catch (error) {
    if (error instanceof HarnessError && error.code === "E_REFERENCE_INVALID") {
      fail("E_SKILLS_REGISTRY_MISSING", `skills registry does not exist: ${control.registryPath}`, { exitCode: 2 });
    }
    throw error;
  }
}

export async function readSkillLock(root, control, { missing = "fail" } = {}) {
  try {
    return parseSkillLockText(await readRepoText(root, control.lockPath, "skills lock"));
  } catch (error) {
    if (error instanceof HarnessError && error.code === "E_REFERENCE_INVALID") {
      if (missing === "null") return null;
      fail("E_SKILLS_LOCK_MISSING", `skills lock does not exist: ${control.lockPath}`, { exitCode: 1, repair: UPDATE_REPAIR });
    }
    throw error;
  }
}

function skillCallsFor(workflow) {
  const calls = new Map();
  for (const stage of Object.values(workflow?.stages ?? {})) {
    for (const call of stage?.skillCalls ?? []) {
      if (!nonEmpty(call?.skill)) continue;
      calls.set(call.skill, (calls.get(call.skill) ?? false) || call.required === true);
    }
  }
  return [...calls.entries()].map(([skill, required]) => ({ skill, required }));
}

export async function inspectSkillsReadiness({ root, workflow, catalog }) {
  const issues = [];
  const warnings = [];
  const entries = new Map((catalog?.skills ?? []).map((entry) => [entry.id, entry]));
  const externalEntries = [...entries.values()].filter((entry) => entry.availability === "lock-owned");
  const calls = skillCallsFor(workflow);
  const skills = [];
  const result = (valid, ready, extra = {}) => ({ valid, ready, issues, warnings, skills, control: null, registryDigest: null, lockDigest: null, ...extra });
  if (externalEntries.length === 0) return result(true, true);

  const control = await resolveSkillControlPaths(root);
  let registry;
  try {
    registry = await readSkillRegistry(root, control);
  } catch (error) {
    const code = error instanceof HarnessError ? error.code : "E_SKILLS_REGISTRY_INVALID";
    issues.push(issue(code, error.message));
    return result(false, false, { control });
  }
  const registryDigest = `sha256:${sha256Hex(JSON.stringify(registry))}`;

  // Catalog -> registry closure: every external entry's sourceId must exist.
  const sourceIds = new Set(registry.sources.map((source) => source.id));
  for (const entry of externalEntries) {
    if (!sourceIds.has(entry.sourceId)) {
      issues.push(issue("E_SKILL_SOURCE_UNKNOWN", `catalog entry "${entry.id}" references unknown skill source "${entry.sourceId}"`, { skill: entry.id, sourceId: entry.sourceId }));
    }
  }
  if (issues.length > 0) return result(false, false, { control, registryDigest });

  let lock = null;
  let lockDigest = null;
  try {
    lock = await readSkillLock(root, control, { missing: "null" });
    lockDigest = lock ? `sha256:${sha256Hex(JSON.stringify(lock))}` : null;
  } catch (error) {
    const code = error instanceof HarnessError ? error.code : "E_SKILLS_LOCK_INVALID";
    issues.push(issue(code, error.message));
    return result(false, false, { control, registryDigest });
  }
  const base = { control, registryDigest, lockDigest };
  if (!lock) {
    issues.push(issue("E_SKILLS_LOCK_MISSING", `skills lock does not exist: ${control.lockPath}`, null, UPDATE_REPAIR));
    return result(true, false, base);
  }
  if (!registryMatchesLock(registry, lock)) {
    issues.push(issue("E_SKILLS_LOCK_STALE", "skills registry source specs differ from the lock", { registry: control.registryPath, lock: control.lockPath }, UPDATE_REPAIR));
    return result(true, false, base);
  }

  // Catalog -> lock closure: every external entry must be lock-owned.
  const lockedSkills = new Map();
  for (const source of lock.sources) for (const skill of source.skills) lockedSkills.set(skill.name, { source, skill });
  for (const entry of externalEntries) {
    if (!lockedSkills.has(entry.id)) {
      issues.push(issue("E_SKILL_LOCK_ENTRY_MISSING", `catalog entry "${entry.id}" is not owned by the skills lock`, { skill: entry.id }, UPDATE_REPAIR));
    }
  }
  if (issues.length > 0) return result(true, false, base);

  // Entity state for the skills this workflow actually calls.
  for (const call of calls) {
    const entry = entries.get(call.skill);
    if (!entry || entry.availability !== "lock-owned") continue;
    const locked = lockedSkills.get(call.skill);
    const inspected = await inspectSkillDirectory(root, call.skill);
    if (inspected.state === "unsafe") {
      issues.push(issue("E_SKILL_TREE_UNSAFE", `skill "${call.skill}" materialization contains a symlink or non-regular file`, { skill: call.skill, path: `${SKILLS_ROOT}/${call.skill}` }));
      continue;
    }
    if (inspected.state === "missing") {
      if (call.required) issues.push(issue("E_SKILL_ENTITY_MISSING", `required skill "${call.skill}" is not materialized`, { skill: call.skill, path: `${SKILLS_ROOT}/${call.skill}` }, SYNC_REPAIR));
      else {
        warnings.push(issue("W_SKILL_UNAVAILABLE", `optional skill "${call.skill}" is not materialized; record it as skipped with a reason in Stage Results`, { skill: call.skill }));
        skills.push({ id: call.skill, sourceId: entry.sourceId, required: call.required, state: "missing" });
      }
      continue;
    }
    if (inspected.digest !== locked.skill.treeDigest) {
      if (call.required) issues.push(issue("E_SKILL_ENTITY_DRIFT", `required skill "${call.skill}" digest differs from the lock`, { skill: call.skill, expected: locked.skill.treeDigest, actual: inspected.digest }, SYNC_REPAIR));
      else {
        warnings.push(issue("W_SKILL_DRIFT", `optional skill "${call.skill}" digest differs from the lock`, { skill: call.skill, expected: locked.skill.treeDigest, actual: inspected.digest }));
        skills.push({ id: call.skill, sourceId: entry.sourceId, required: call.required, state: "drifted" });
      }
      continue;
    }
    skills.push({ id: call.skill, sourceId: entry.sourceId, required: call.required, state: "ready" });
  }
  const invalid = issues.some((entry) => new Set(["E_SKILL_TREE_UNSAFE"]).has(entry.code));
  return result(!invalid, issues.length === 0, base);
}
