#!/usr/bin/env node
// skills-sync.mjs — 按 .agents/skills.sources.json 从 Git 仓库同步外部 Skills。
// 幂等、零第三方依赖。只写三类产物：
//   .agents/skills/<name>/    受管外部 Skill 目录（被生成的 .gitignore 排除，不入库）
//   .agents/skills.lock.json  解析后的 commit 锁定，需提交以复现
//   .agents/skills/.gitignore 本脚本生成，按名排除受管目录
// 绝不覆盖锁文件之外的既有 Skill 目录（Overlay 自带或手工安装）。
//
//   node scripts/skills-sync.mjs [--root <dir>] [--force]
//
// 输出（Agent 可直接读取）:
//   SYNCED <name> @ <sha>   新拉取或内容变化
//   KEPT   <name> @ <sha>   已锁定且磁盘一致，未访问网络
//   PRUNED <name>           来源移除后清理的受管目录
//
// 退出码: 0 成功；1 同步失败；2 manifest 或锁文件无法解析。

import { execFile } from "node:child_process";
import { access, cp, mkdir, mkdtemp, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

const MANIFEST_REL = ".agents/skills.sources.json";
const LOCK_REL = ".agents/skills.lock.json";
const GITIGNORE_HEADER = "# Generated by scripts/skills-sync.mjs — managed external skills, do not edit.";
const PINNED_SHA = /^[0-9a-f]{40}$/;
const SAFE_NAME = /^[A-Za-z0-9._-]+$/;

function fail(message, code = 1) {
  process.stderr.write(`ERROR skills-sync: ${message}\n`);
  process.exit(code);
}

async function exists(path) {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function git(args) {
  try {
    const { stdout } = await execFileAsync("git", args, {
      env: { ...process.env, GIT_TERMINAL_PROMPT: "0" },
      timeout: 120_000,
      maxBuffer: 4 * 1024 * 1024,
    });
    return stdout;
  } catch (error) {
    const detail = typeof error.stderr === "string" && error.stderr.trim() !== "" ? error.stderr.trim() : error.message;
    throw new Error(`git ${args.join(" ")}: ${detail}`);
  }
}

// 来源身份：repo+path+ref+过滤条件；harness-check.mjs 用同一规则比对清单与锁文件。
function sourceKeyOf(entry) {
  return JSON.stringify([entry.repo, entry.path, entry.ref, entry.only ?? null, entry.exclude ?? null]);
}

function isNonEmptyString(value) {
  return typeof value === "string" && value.trim() !== "";
}

function readManifest(manifestPath) {
  return readFile(manifestPath, "utf8")
    .then((raw) => {
      try {
        return JSON.parse(raw);
      } catch (error) {
        fail(`${MANIFEST_REL} is not valid JSON: ${error.message}`, 2);
      }
    })
    .then((manifest) => {
      if (typeof manifest !== "object" || manifest === null || Array.isArray(manifest)) {
        fail(`${MANIFEST_REL} must contain a JSON object.`, 2);
      }
      return manifest;
    });
}

function validateSources(sources) {
  for (const [index, entry] of sources.entries()) {
    if (typeof entry !== "object" || entry === null || Array.isArray(entry)) {
      fail(`sources[${index}] must be an object.`, 2);
    }
    for (const field of ["repo", "path", "ref"]) {
      if (!isNonEmptyString(entry[field])) {
        fail(`sources[${index}] must declare ${field} as a non-empty string.`, 2);
      }
    }
    if (entry.path.split("/").includes("..")) {
      fail(`sources[${index}].path must not contain "..".`, 2);
    }
    for (const field of ["only", "exclude"]) {
      if (entry[field] !== undefined && (!Array.isArray(entry[field]) || entry[field].some((item) => !isNonEmptyString(item)))) {
        fail(`sources[${index}].${field} must be an array of non-empty strings.`, 2);
      }
    }
  }
}

async function readLockfile(root) {
  const lockPath = join(root, LOCK_REL);
  if (!(await exists(lockPath))) return { managed: [] };
  let value;
  try {
    value = JSON.parse(await readFile(lockPath, "utf8"));
  } catch (error) {
    fail(`${LOCK_REL} is not valid JSON: ${error.message}. Fix it or delete it and re-run sync.`, 2);
  }
  return { managed: Array.isArray(value?.managed) ? value.managed : [] };
}

async function skillName(dir) {
  try {
    const raw = await readFile(join(dir, "SKILL.md"), "utf8");
    const frontmatter = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    const name = frontmatter?.[1].match(/^name:\s*["']?(.+?)["']?\s*$/m)?.[1];
    if (name) return name;
  } catch {
    // 读取失败时回退到目录名。
  }
  return basename(dir);
}

// 返回 [{ absDir, relDir, name }]；relDir 相对 source.path 根。含 SKILL.md 的目录不再下钻。
async function discoverSkills(startDir) {
  const skills = [];
  async function walk(dir, rel) {
    const entries = await readdir(dir, { withFileTypes: true });
    if (entries.some((entry) => entry.isFile() && entry.name === "SKILL.md")) {
      skills.push({ absDir: dir, relDir: rel, name: await skillName(dir) });
      return;
    }
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      if (entry.name === ".git" || entry.name === "node_modules") continue;
      await walk(join(dir, entry.name), rel ? `${rel}/${entry.name}` : entry.name);
    }
  }
  await walk(startDir, "");
  return skills;
}

function filterMatches(pattern, skill) {
  if (pattern.endsWith("/")) {
    return skill.relDir.startsWith(pattern) || skill.relDir === pattern.slice(0, -1);
  }
  return skill.name === pattern || basename(skill.relDir) === pattern;
}

function selectedByFilters(skill, source) {
  const only = Array.isArray(source.only) ? source.only : null;
  const exclude = Array.isArray(source.exclude) ? source.exclude : [];
  if (only && !only.some((pattern) => filterMatches(pattern, skill))) return false;
  if (exclude.some((pattern) => filterMatches(pattern, skill))) return false;
  return true;
}

async function main(argv) {
  const args = [...argv];
  let root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
  const rootIndex = args.indexOf("--root");
  if (rootIndex !== -1) {
    const value = args[rootIndex + 1];
    if (!value) fail("--root requires a directory argument.", 2);
    root = resolve(value);
    args.splice(rootIndex, 2);
  }
  const forceIndex = args.indexOf("--force");
  const force = forceIndex !== -1;
  if (force) args.splice(forceIndex, 1);
  if (args.length > 0) {
    process.stdout.write("Usage: node scripts/skills-sync.mjs [--root <dir>] [--force]\n");
    process.exit(args[0] === "help" || args[0] === "--help" || args[0] === "-h" ? 0 : 2);
  }

  let sources = [];
  let skillsRoot = ".agents/skills";
  const manifestPath = join(root, MANIFEST_REL);
  if (await exists(manifestPath)) {
    const manifest = await readManifest(manifestPath);
    if (manifest.skillsRoot !== undefined) {
      if (!isNonEmptyString(manifest.skillsRoot) || manifest.skillsRoot.split("/").includes("..")) {
        fail(`${MANIFEST_REL} skillsRoot must be a safe project-relative path.`, 2);
      }
      skillsRoot = manifest.skillsRoot.trim();
    }
    sources = Array.isArray(manifest.sources) ? manifest.sources : [];
    validateSources(sources);
  }

  const prior = await readLockfile(root);
  const skillsRootAbs = join(root, skillsRoot);
  const tmp = await mkdtemp(join(tmpdir(), "skills-sync-"));
  const produced = [];
  const usedNames = new Map();

  function registerName(name, source) {
    if (!SAFE_NAME.test(name)) fail(`Skill name "${name}" has illegal characters (allowed: A-Z a-z 0-9 . _ -).`);
    const existing = usedNames.get(name);
    if (existing) {
      fail(`Two sources produce skill "${name}" (${existing} and ${source.repo}#${source.path}); disambiguate with only/exclude.`);
    }
    usedNames.set(name, `${source.repo}#${source.path}`);
  }

  try {
    for (const [index, source] of sources.entries()) {
      const key = sourceKeyOf(source);
      const priorForSource = prior.managed.filter((entry) => sourceKeyOf(entry) === key);
      const reusable =
        !force &&
        PINNED_SHA.test(source.ref) &&
        priorForSource.length > 0 &&
        priorForSource.every((entry) => entry.resolved === source.ref) &&
        (await Promise.all(priorForSource.map((entry) => exists(join(skillsRootAbs, entry.name, "SKILL.md"))))).every(Boolean);
      if (reusable) {
        for (const entry of priorForSource) {
          registerName(entry.name, source);
          produced.push(entry);
          process.stdout.write(`KEPT ${entry.name} @ ${entry.resolved.slice(0, 12)}\n`);
        }
        continue;
      }

      const workDir = join(tmp, `source-${index}`);
      let resolved;
      try {
        await git(["init", "-q", workDir]);
        await git(["-C", workDir, "fetch", "-q", "--depth", "1", source.repo, source.ref]);
        await git(["-C", workDir, "checkout", "-q", "FETCH_HEAD"]);
        resolved = (await git(["-C", workDir, "rev-parse", "HEAD"])).trim();
      } catch (error) {
        fail(`Cannot fetch ${source.repo} @ ${source.ref}: ${error.message}. Check network, authentication and that ref is a tag or full commit SHA.`);
      }

      const startDir = join(workDir, source.path);
      if (!(await exists(startDir))) {
        fail(`path "${source.path}" does not exist in ${source.repo} @ ${source.ref}.`);
      }
      const discovered = await discoverSkills(startDir);
      if (discovered.length === 0) {
        fail(`No directory with SKILL.md found under "${source.path}" in ${source.repo}.`);
      }
      const selected = discovered.filter((skill) => selectedByFilters(skill, source));
      if (selected.length === 0) {
        fail(`only/exclude filters in ${MANIFEST_REL} leave no skills from ${source.repo}#${source.path}.`);
      }

      for (const skill of selected) {
        registerName(skill.name, source);
        const target = join(skillsRootAbs, skill.name);
        if ((await exists(target)) && !prior.managed.some((entry) => entry.name === skill.name)) {
          fail(`Refusing to overwrite ${skillsRoot}/${skill.name}: it is not managed by this script. Remove it by hand or rename the incoming skill.`);
        }
        await rm(target, { recursive: true, force: true });
        await cp(skill.absDir, target, { recursive: true });
        produced.push({
          name: skill.name,
          repo: source.repo,
          path: source.path,
          ref: source.ref,
          ...(source.only ? { only: source.only } : {}),
          ...(source.exclude ? { exclude: source.exclude } : {}),
          resolved,
        });
        process.stdout.write(`SYNCED ${skill.name} @ ${resolved.slice(0, 12)}\n`);
      }
    }

    // 清理不再由任何来源产生的受管目录。
    const producedNames = new Set(produced.map((entry) => entry.name));
    for (const old of prior.managed) {
      if (!producedNames.has(old.name)) {
        await rm(join(skillsRootAbs, old.name), { recursive: true, force: true });
        process.stdout.write(`PRUNED ${old.name}\n`);
      }
    }

    await mkdir(skillsRootAbs, { recursive: true });
    const gitignorePath = join(skillsRootAbs, ".gitignore");
    if (produced.length > 0) {
      const lines = [GITIGNORE_HEADER, ...[...producedNames].sort().map((name) => `/${name}/`), ""];
      await writeFile(gitignorePath, lines.join("\n"));
    } else if (await exists(gitignorePath)) {
      const raw = await readFile(gitignorePath, "utf8");
      if (raw.startsWith(GITIGNORE_HEADER)) await rm(gitignorePath);
    }

    const lockPath = join(root, LOCK_REL);
    if (produced.length > 0) {
      const lock = {
        version: 1,
        skillsRoot,
        managed: produced.sort((left, right) => left.name.localeCompare(right.name)),
      };
      await writeFile(lockPath, JSON.stringify(lock, null, 2) + "\n");
    } else {
      await rm(lockPath, { force: true });
    }

    process.stdout.write(`OK skills-sync: ${producedNames.size} skills from ${sources.length} sources\n`);
  } finally {
    await rm(tmp, { recursive: true, force: true });
  }
}

main(process.argv.slice(2)).catch((error) => {
  process.stderr.write(`ERROR skills-sync.internal: ${error instanceof Error ? error.message : String(error)}\n`);
  process.exit(2);
});
